/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// Everything `npm run generate` derives, computed for any checkout root so a
// test can run it against a temporary copy:
//
// - refs/<profile>.tfmap.json from refs/manifest.json and the districts;
// - flows/hh-district-<slug> and flows/hh-queue-experience-<slug>, and the
//   one flows/hh-district-menu, each a FlowDoc plus its `.flow.ts` companion.
//
// A companion is codegen output (@flow-as-code/core's codegen, the one the
// studio and flow-cli use), so it is exactly what a studio save of the
// document would write. It carries a two-line banner as `@keep` comments,
// which codegen re-attaches on every regeneration, and the document's
// meta.sourceHash is the companion's hash, so the pair opens in sync.

import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { codegen, serialize, synth, type Flow } from "@flow-as-code/core";
import { loadDistricts, type District } from "./config.js";
import { districtFlow, districtMenuFlow, queueExperienceFlow } from "./flows.js";
import { addressMap, loadManifest, manifestProblems, serializeMap } from "./refs.js";

/** Recorded in meta.generator of every generated FlowDoc. */
export const GENERATOR = "hollow-hour-example generators/districts.ts";

export const BANNER = [
  "// @keep GENERATED by generators/districts.ts from districts.config.json.",
  "// @keep Edit the config and run `npm run generate`; edits made here are overwritten.",
];

/** A file name in flows/ that belongs to the generator (hh-district-menu included). */
export const GENERATED_FLOW_FILE =
  /^hh-(?:district|queue-experience)-[a-z0-9]+(?:-[a-z0-9]+)*\.(?:flowdoc\.json|flow\.ts)$/;

const sha256 = (text: string) => createHash("sha256").update(text, "utf8").digest("hex");

/** One generated flow as the two files written for it, keyed by path under the root. */
export function flowFiles(flow: Flow): Map<string, string> {
  const doc = synth(flow, { includeMeta: false });
  const companion = codegen(doc, { keep: { beforeExport: BANNER, beforeBlock: new Map() } });
  const text = serialize({
    ...doc,
    meta: { generator: GENERATOR, sourceHash: `sha256:${sha256(companion)}`, sourceKind: "ts" },
  });
  return new Map([
    [`flows/${doc.name}.flow.ts`, companion],
    [`flows/${doc.name}.flowdoc.json`, text],
  ]);
}

/** Every generated flow file for these districts, keyed by path under the root. */
export function generatedFlowFiles(districts: readonly District[]): Map<string, string> {
  const out = new Map<string, string>(flowFiles(districtMenuFlow(districts)));
  for (const d of districts) {
    for (const flow of [districtFlow(d, districts), queueExperienceFlow(d, districts)]) {
      for (const [path, text] of flowFiles(flow)) out.set(path, text);
    }
  }
  return out;
}

/** Every derived file, keyed by path under `root`. */
export function derivedFiles(root: string): Map<string, string> {
  const districts = loadDistricts(join(root, "districts.config.json"));
  const manifest = loadManifest(join(root, "refs", "manifest.json"));
  const problems = manifestProblems(manifest);
  if (problems.length > 0) throw new Error(`refs/manifest.json:\n  ${problems.join("\n  ")}`);
  const out = new Map<string, string>();
  for (const profile of Object.keys(manifest.profiles)) {
    out.set(`refs/${profile}.tfmap.json`, serializeMap(addressMap(manifest, districts, profile)));
  }
  for (const [path, text] of generatedFlowFiles(districts)) out.set(path, text);
  return out;
}

export interface GenerateResult {
  /** Paths (under the root) whose content was, or in check mode would be, written. */
  changed: string[];
  /** Generated flow files on disk that no district produces any more. */
  orphaned: string[];
  total: number;
}

/**
 * Writes every derived file under `root` and removes orphaned generated flows,
 * or with `check` writes nothing and reports what differs.
 */
export function generate(root: string, options: { check?: boolean } = {}): GenerateResult {
  const outputs = derivedFiles(root);
  const changed: string[] = [];
  for (const [path, text] of outputs) {
    const file = join(root, path);
    const current = existsSync(file) ? readFileSync(file, "utf8") : undefined;
    if (current === text) continue;
    changed.push(path);
    if (options.check !== true) writeFileSync(file, text);
  }
  const flowsDir = join(root, "flows");
  const orphaned = (existsSync(flowsDir) ? readdirSync(flowsDir) : [])
    .filter((f) => GENERATED_FLOW_FILE.test(f) && !outputs.has(`flows/${f}`))
    .map((f) => `flows/${f}`)
    .sort();
  if (options.check !== true) {
    for (const path of orphaned) rmSync(join(root, path));
  }
  return { changed: changed.sort(), orphaned, total: outputs.size };
}
