// Generated by @flow-as-code/core codegen from hh-agent-hold.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { Flow, MessageParticipantIteratively } from "@flow-as-code/core";

export function hhAgentHold(): Flow {
  return new Flow({
    name: "hh-agent-hold",
    description: "What the crew member hears while the caller has them on hold. One loop of prompts and nothing else: MessageParticipant and every terminal type are illegal in hold flows, and a loop with no next ends the flow. Reads contact attributes only.",
    connectType: "AGENT_HOLD",
  }).add(
    new MessageParticipantIteratively({
      id: "on-hold",
      messages: [{ text: "Caller on hold. Grade $.Attributes.gradeName." }],
    }),
  );
}
