// Generated by @flow-as-code/core codegen from hh-agent-whisper.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { EndFlowExecution, Flow, MessageParticipant } from "@flow-as-code/core";

export function hhAgentWhisper(): Flow {
  return new Flow({
    name: "hh-agent-whisper",
    description: "What the crew hears before the caller joins: district, grade name and the advice already given. Reads contact attributes only.",
    connectType: "AGENT_WHISPER",
  }).add(
    new MessageParticipant({
      id: "brief-the-crew",
      text: "$.Attributes.districtName call. Grade: $.Attributes.gradeName. Advice given: $.Attributes.advice",
      next: "done",
      onError: "done",
    }),
    new EndFlowExecution({ id: "done" }),
  );
}
