// Generated by @flow-as-code/core codegen from hh-customer-hold.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { Flow, MessageParticipantIteratively } from "@flow-as-code/core";

export function hhCustomerHold(): Flow {
  return new Flow({
    name: "hh-customer-hold",
    description: "What the caller hears while a crew member has them on hold. One loop of prompts and nothing else: MessageParticipant and every terminal type are illegal in hold flows, and a loop with no next ends the flow. Reads contact attributes only.",
    connectType: "CUSTOMER_HOLD",
  }).add(
    new MessageParticipantIteratively({
      id: "on-hold",
      messages: [
        { text: "You are on hold with the $.Attributes.districtName crew. Keep the lights on." },
      ],
    }),
  );
}
