// Generated by @flow-as-code/core codegen from hh-customer-whisper.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { EndFlowExecution, Flow, MessageParticipant } from "@flow-as-code/core";

export function hhCustomerWhisper(): Flow {
  return new Flow({
    name: "hh-customer-whisper",
    description: "What the caller hears as a district crew picks up. Reads contact attributes only.",
    connectType: "CUSTOMER_WHISPER",
  }).add(
    new MessageParticipant({
      id: "connecting",
      text: "You are through to the $.Attributes.districtName crew. Stay with others and keep the lights on.",
      next: "done",
      onError: "done",
    }),
    new EndFlowExecution({ id: "done" }),
  );
}
