// Generated by @flow-as-code/core codegen from hh-district-graveyard-hill.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  CheckHoursOfOperation,
  CheckMetricData,
  DisconnectParticipant,
  Flow,
  GetMetricData,
  MessageParticipant,
  Refs,
  TransferContactToQueue,
  UpdateContactAttributes,
  UpdateContactEventHooks,
  UpdateContactTargetQueue,
  UpdateFlowAttributes,
} from "@flow-as-code/core";

// @keep GENERATED by generators/districts.ts from districts.config.json.
// @keep Edit the config and run `npm run generate`; edits made here are overwritten.
export function hhDistrictGraveyardHill(): Flow {
  return new Flow({
    name: "hh-district-graveyard-hill",
    description: "Dispatch for Graveyard Hill. Generated from districts.config.json by generators/districts.ts; edit the config, not this flow.",
    connectType: "CONTACT_FLOW",
  }).add(
    new UpdateContactTargetQueue({
      id: "set-crew-queue",
      queue: Refs.queue("graveyard-hill-crew"),
      next: "set-customer-whisper",
      onError: "hand-to-dispatch",
    }),
    new UpdateContactEventHooks({
      id: "set-customer-whisper",
      hook: "CustomerWhisper",
      flow: Refs.flow("hh-customer-whisper"),
      next: "set-agent-whisper",
      onError: "set-agent-whisper",
    }),
    new UpdateContactEventHooks({
      id: "set-agent-whisper",
      hook: "AgentWhisper",
      flow: Refs.flow("hh-agent-whisper"),
      next: "set-queue-experience",
      onError: "set-queue-experience",
    }),
    new UpdateContactEventHooks({
      id: "set-queue-experience",
      hook: "CustomerQueue",
      flow: Refs.flow("hh-queue-experience-graveyard-hill"),
      next: "note-overflow-crew",
      onError: "note-overflow-crew",
    }),
    new UpdateFlowAttributes({
      id: "note-overflow-crew",
      attributes: { overflowCrew: "Old Town" },
      next: "check-hours",
      onError: "check-hours",
    }),
    new CheckHoursOfOperation({
      id: "check-hours",
      hours: Refs.hours("graveyard-hill"),
      onInHours: "check-staffing",
      onOutOfHours: "after-hours",
      onError: "check-staffing",
    }),
    new CheckMetricData({
      id: "check-staffing",
      metric: "NumberOfAgentsAvailable",
      queue: Refs.queue("graveyard-hill-crew"),
      branches: [{ operator: "NumberGreaterThan", operand: "0", target: "crew-ready" }],
      onNoMatch: "read-queue",
      onError: "transfer-to-crew",
    }),
    new MessageParticipant({
      id: "crew-ready",
      text: "The Graveyard Hill crew has someone free. Connecting you now.",
      next: "transfer-to-crew",
      onError: "transfer-to-crew",
    }),
    new GetMetricData({
      id: "read-queue",
      queue: Refs.queue("graveyard-hill-crew"),
      next: "announce-line",
      onError: "transfer-to-crew",
    }),
    new MessageParticipant({
      id: "announce-line",
      text: "The Graveyard Hill crew is out on calls. Callers ahead of you: $.Metrics.Queue.Size. Stay on the line and we will keep your place.",
      next: "transfer-to-crew",
      onError: "transfer-to-crew",
    }),
    new TransferContactToQueue({
      id: "transfer-to-crew",
      next: "hang-up",
      onQueueAtCapacity: "crew-full",
      onError: "apologize",
    }),
    new MessageParticipant({
      id: "crew-full",
      text: "The Graveyard Hill crew is full tonight. Moving you to the $.FlowAttributes.overflowCrew crew.",
      next: "note-overflow-district",
      onError: "note-overflow-district",
    }),
    new UpdateContactAttributes({
      id: "note-overflow-district",
      attributes: { district: "old-town", districtName: "Old Town" },
      next: "set-overflow-queue-experience",
      onError: "set-overflow-queue-experience",
    }),
    new UpdateContactEventHooks({
      id: "set-overflow-queue-experience",
      hook: "CustomerQueue",
      flow: Refs.flow("hh-queue-experience-old-town"),
      next: "set-overflow-queue",
      onError: "set-overflow-queue",
    }),
    new UpdateContactTargetQueue({
      id: "set-overflow-queue",
      queue: Refs.queue("old-town-crew"),
      next: "transfer-to-overflow",
      onError: "apologize",
    }),
    new TransferContactToQueue({
      id: "transfer-to-overflow",
      next: "hang-up",
      onQueueAtCapacity: "lines-busy",
      onError: "apologize",
    }),
    new MessageParticipant({
      id: "after-hours",
      text: "The Graveyard Hill crew is off shift right now. Night crews start at 4 in the afternoon. If anyone is hurt or in danger, call your local emergency number (911 in the US).",
      next: "hang-up",
      onError: "hang-up",
    }),
    new MessageParticipant({
      id: "hand-to-dispatch",
      text: "Let me put you through to a dispatcher.",
      next: "note-dispatch",
      onError: "note-dispatch",
    }),
    new UpdateContactAttributes({
      id: "note-dispatch",
      attributes: { districtName: "Dispatch" },
      next: "set-dispatch-customer-whisper",
      onError: "set-dispatch-customer-whisper",
    }),
    new UpdateContactEventHooks({
      id: "set-dispatch-customer-whisper",
      hook: "CustomerWhisper",
      flow: Refs.flow("hh-customer-whisper"),
      next: "set-dispatch-agent-whisper",
      onError: "set-dispatch-agent-whisper",
    }),
    new UpdateContactEventHooks({
      id: "set-dispatch-agent-whisper",
      hook: "AgentWhisper",
      flow: Refs.flow("hh-agent-whisper"),
      next: "set-dispatch-queue",
      onError: "set-dispatch-queue",
    }),
    new UpdateContactTargetQueue({
      id: "set-dispatch-queue",
      queue: Refs.queue("dispatch-overflow"),
      next: "transfer-to-dispatch",
      onError: "apologize",
    }),
    new TransferContactToQueue({
      id: "transfer-to-dispatch",
      next: "hang-up",
      onQueueAtCapacity: "lines-busy",
      onError: "apologize",
    }),
    new MessageParticipant({
      id: "lines-busy",
      text: "Every crew is out on a call. Please call back in a few minutes.",
      next: "hang-up",
      onError: "hang-up",
    }),
    new MessageParticipant({
      id: "apologize",
      text: "Something went wrong on our side. Please call back in a few minutes.",
      next: "hang-up",
      onError: "hang-up",
    }),
    new DisconnectParticipant({ id: "hang-up" }),
  );
}
