// Generated by @flow-as-code/core codegen from hh-dead-hold.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { Flow, MessageParticipantIteratively } from "@flow-as-code/core";

export function hhDeadHold(): Flow {
  return new Flow({
    name: "hh-dead-hold",
    description: "What a departed caller hears while the liaison has them on hold. One loop of prompts and nothing else, as every hold flow here.",
    connectType: "CUSTOMER_HOLD",
  }).add(
    new MessageParticipantIteratively({
      id: "on-hold",
      messages: [{ text: "Hold music is wasted on you, we know. Back shortly." }],
    }),
  );
}
