// Generated by @flow-as-code/core codegen from hh-dead-line.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  CheckHoursOfOperation,
  DisconnectParticipant,
  Flow,
  MessageParticipant,
  Refs,
  TransferContactToQueue,
  UpdateContactAttributes,
  UpdateContactCallbackNumber,
  UpdateContactEventHooks,
  UpdateContactRecordingBehavior,
  UpdateContactRoutingBehavior,
  UpdateContactTargetQueue,
  jsonPath,
} from "@flow-as-code/core";

export function hhDeadLine(): Flow {
  return new Flow({
    name: "hh-dead-line",
    description: "The line for the departed, reached from hh-hotline-main when plane-check says the caller is beyond. Welcome first, then agent-only recording, the four hooks, patience, the callback number, the hours that never close, and the Queue of the Dead.",
    connectType: "CONTACT_FLOW",
  }).add(
    new MessageParticipant({
      id: "dead-welcome",
      text: "You have reached the Hollow Hour line for the departed. Calls are recorded, but only our liaison's side, never yours. You are welcome here, and we are glad you called.",
      next: "record-agent-only",
      onError: "record-agent-only",
    }),
    new UpdateContactRecordingBehavior({
      id: "record-agent-only",
      recordedParticipants: ["Agent"],
      next: "set-dead-whisper",
    }),
    new UpdateContactEventHooks({
      id: "set-dead-whisper",
      hook: "AgentWhisper",
      flow: Refs.flow("hh-dead-whisper"),
      next: "set-dead-hold",
      onError: "set-dead-hold",
    }),
    new UpdateContactEventHooks({
      id: "set-dead-hold",
      hook: "CustomerHold",
      flow: Refs.flow("hh-dead-hold"),
      next: "set-dead-queue-experience",
      onError: "set-dead-queue-experience",
    }),
    new UpdateContactEventHooks({
      id: "set-dead-queue-experience",
      hook: "CustomerQueue",
      flow: Refs.flow("hh-dead-queue-experience"),
      next: "set-dead-agent-hold",
      onError: "set-dead-agent-hold",
    }),
    new UpdateContactEventHooks({
      id: "set-dead-agent-hold",
      hook: "AgentHold",
      flow: Refs.flow("hh-agent-hold"),
      next: "note-beyond",
      onError: "note-beyond",
    }),
    new UpdateContactAttributes({
      id: "note-beyond",
      attributes: { district: "beyond", districtName: "Beyond", gradeName: "Departed" },
      next: "set-patience",
      onError: "set-patience",
    }),
    new UpdateContactRoutingBehavior({
      id: "set-patience",
      queueTimeAdjustmentSeconds: -300,
      next: "set-callback-number",
    }),
    new UpdateContactCallbackNumber({
      id: "set-callback-number",
      callbackNumber: jsonPath("$.CustomerEndpoint.Address"),
      next: "check-dead-hours",
      onInvalidNumber: "cannot-ring-back",
      onNotDialable: "cannot-ring-back",
    }),
    new MessageParticipant({
      id: "cannot-ring-back",
      text: "We cannot ring you back where you are, so stay on the line.",
      next: "check-dead-hours",
      onError: "check-dead-hours",
    }),
    new CheckHoursOfOperation({
      id: "check-dead-hours",
      hours: Refs.hours("the-dead"),
      onInHours: "set-dead-queue",
      onOutOfHours: "set-dead-queue",
      onError: "set-dead-queue",
    }),
    new UpdateContactTargetQueue({
      id: "set-dead-queue",
      queue: Refs.queue("the-dead"),
      next: "transfer-to-dead",
      onError: "apologize",
    }),
    new TransferContactToQueue({
      id: "transfer-to-dead",
      next: "hang-up",
      onQueueAtCapacity: "dead-full",
      onError: "apologize",
    }),
    new MessageParticipant({
      id: "dead-full",
      text: "The Queue of the Dead is full tonight, which is saying something. Call back after midnight; we will still be here, and so will you.",
      next: "hang-up",
      onError: "hang-up",
    }),
    new MessageParticipant({
      id: "apologize",
      text: "Something went wrong on our side. Please call back in a few minutes; you have the time.",
      next: "hang-up",
      onError: "hang-up",
    }),
    new DisconnectParticipant({ id: "hang-up" }),
  );
}
