// Generated by @flow-as-code/core codegen from hh-dead-whisper.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { EndFlowExecution, Flow, MessageParticipant } from "@flow-as-code/core";

export function hhDeadWhisper(): Flow {
  return new Flow({
    name: "hh-dead-whisper",
    description: "What the spectral liaison hears before a departed caller joins. Static copy; the dead carry no grade.",
    connectType: "AGENT_WHISPER",
  }).add(
    new MessageParticipant({
      id: "brief-the-liaison",
      text: "Spectral liaison call. Be patient; they have waited a long time.",
      next: "done",
      onError: "done",
    }),
    new EndFlowExecution({ id: "done" }),
  );
}
