// Generated by @flow-as-code/core codegen from hh-district-menu.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  DisconnectParticipant,
  Flow,
  GetParticipantInput,
  MessageParticipant,
  Refs,
  TransferContactToQueue,
  TransferToFlow,
  UpdateContactAttributes,
  UpdateContactEventHooks,
  UpdateContactTargetQueue,
} from "@flow-as-code/core";

// @keep GENERATED by generators/districts.ts from districts.config.json.
// @keep Edit the config and run `npm run generate`; edits made here are overwritten.
export function hhDistrictMenu(): Flow {
  return new Flow({
    name: "hh-district-menu",
    description: "The keypad district menu, one key per district. Generated from districts.config.json by generators/districts.ts; edit the config, not this flow.",
    connectType: "CONTACT_FLOW",
  }).add(
    new GetParticipantInput({
      id: "ask-district",
      text: "Where are you calling from? For Old Town, press 1. For Harborside, press 2. For Graveyard Hill, press 3.",
      timeoutSeconds: 8,
      branches: [
        { digit: "1", target: "route-old-town" },
        { digit: "2", target: "route-harborside" },
        { digit: "3", target: "route-graveyard-hill" },
      ],
      onTimeout: "hand-to-dispatch",
      onNoMatch: "hand-to-dispatch",
      onError: "hand-to-dispatch",
    }),
    new UpdateContactAttributes({
      id: "route-old-town",
      attributes: { district: "old-town", districtName: "Old Town" },
      next: "to-old-town",
      onError: "hand-to-dispatch",
    }),
    new TransferToFlow({
      id: "to-old-town",
      flow: Refs.flow("hh-district-old-town"),
      next: "hang-up",
      onError: "hand-to-dispatch",
    }),
    new UpdateContactAttributes({
      id: "route-harborside",
      attributes: { district: "harborside", districtName: "Harborside" },
      next: "to-harborside",
      onError: "hand-to-dispatch",
    }),
    new TransferToFlow({
      id: "to-harborside",
      flow: Refs.flow("hh-district-harborside"),
      next: "hang-up",
      onError: "hand-to-dispatch",
    }),
    new UpdateContactAttributes({
      id: "route-graveyard-hill",
      attributes: { district: "graveyard-hill", districtName: "Graveyard Hill" },
      next: "to-graveyard-hill",
      onError: "hand-to-dispatch",
    }),
    new TransferToFlow({
      id: "to-graveyard-hill",
      flow: Refs.flow("hh-district-graveyard-hill"),
      next: "hang-up",
      onError: "hand-to-dispatch",
    }),
    new MessageParticipant({
      id: "hand-to-dispatch",
      text: "Let me put you through to a dispatcher.",
      next: "note-dispatch",
      onError: "note-dispatch",
    }),
    new UpdateContactAttributes({
      id: "note-dispatch",
      attributes: { districtName: "Dispatch" },
      next: "set-dispatch-customer-whisper",
      onError: "set-dispatch-customer-whisper",
    }),
    new UpdateContactEventHooks({
      id: "set-dispatch-customer-whisper",
      hook: "CustomerWhisper",
      flow: Refs.flow("hh-customer-whisper"),
      next: "set-dispatch-agent-whisper",
      onError: "set-dispatch-agent-whisper",
    }),
    new UpdateContactEventHooks({
      id: "set-dispatch-agent-whisper",
      hook: "AgentWhisper",
      flow: Refs.flow("hh-agent-whisper"),
      next: "set-dispatch-queue",
      onError: "set-dispatch-queue",
    }),
    new UpdateContactTargetQueue({
      id: "set-dispatch-queue",
      queue: Refs.queue("dispatch-overflow"),
      next: "transfer-to-dispatch",
      onError: "apologize",
    }),
    new TransferContactToQueue({
      id: "transfer-to-dispatch",
      next: "hang-up",
      onQueueAtCapacity: "lines-busy",
      onError: "apologize",
    }),
    new MessageParticipant({
      id: "lines-busy",
      text: "Every crew is out on a call. Please call back in a few minutes.",
      next: "hang-up",
      onError: "hang-up",
    }),
    new MessageParticipant({
      id: "apologize",
      text: "Something went wrong on our side. Please call back in a few minutes.",
      next: "hang-up",
      onError: "hang-up",
    }),
    new DisconnectParticipant({ id: "hang-up" }),
  );
}
