// Generated by @flow-as-code/core codegen from hh-dead-queue-experience.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { EndFlowExecution, Flow, Loop, MessageParticipantIteratively } from "@flow-as-code/core";

export function hhDeadQueueExperience(): Flow {
  return new Flow({
    name: "hh-dead-queue-experience",
    description: "The Queue of the Dead: what a departed caller hears in queue. A loop of reassurance that polls a few times, then settles. No dequeue: there is no other queue for them.",
    connectType: "CUSTOMER_QUEUE",
  }).add(
    new Loop({
      id: "keep-vigil",
      count: 3,
      onContinue: "reassure",
      onDone: "settle-in",
    }),
    new MessageParticipantIteratively({
      id: "reassure",
      messages: [
        {
          text: "You are in the Queue of the Dead. A liaison will be with you; you have our word.",
        },
        { text: "The living go first tonight, but nobody here is forgotten." },
      ],
      interruptFrequencySeconds: 30,
      onInterrupt: "keep-vigil",
      onError: "done",
    }),
    new MessageParticipantIteratively({
      id: "settle-in",
      messages: [{ text: "Still with you. Rest if you can; the liaison knows you are waiting." }],
    }),
    new EndFlowExecution({ id: "done" }),
  );
}
