// Generated by @flow-as-code/core codegen from hh-offer-callback.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  CreateCallbackContact,
  EndFlowModuleExecution,
  FlowModule,
  MessageParticipant,
  Refs,
  UpdateContactCallbackNumber,
  jsonPath,
} from "@flow-as-code/core";

export function hhOfferCallback(): FlowModule {
  return new FlowModule({
    name: "hh-offer-callback",
    description: "Takes a callback for a caller who cannot wait: the caller's own number, then a callback contact in the dispatch-overflow queue, which a crew works when the night shift starts. Invoked by hh-district-<slug> after hours and when both crews are full.",
    settings: { InputParameters: [], OutputParameters: [], Transitions: [] },
  }).add(
    new UpdateContactCallbackNumber({
      id: "set-callback-number",
      callbackNumber: jsonPath("$.CustomerEndpoint.Address"),
      next: "create-callback",
      onInvalidNumber: "cannot-ring-back",
      onNotDialable: "cannot-ring-back",
    }),
    new CreateCallbackContact({
      id: "create-callback",
      queue: Refs.queue("dispatch-overflow"),
      initialCallDelaySeconds: 60,
      maximumConnectionAttempts: 2,
      retryDelaySeconds: 600,
      next: "callback-taken",
      onError: "callback-refused",
    }),
    new MessageParticipant({
      id: "callback-taken",
      text: "You are on the list. A crew will call when the night shift starts, or sooner if one comes free. Keep the lights on until then.",
      next: "done",
      onError: "done",
    }),
    new MessageParticipant({
      id: "callback-refused",
      text: "We cannot take a callback right now; please call back in a few minutes.",
      next: "done",
      onError: "done",
    }),
    new MessageParticipant({
      id: "cannot-ring-back",
      text: "We cannot ring you back at the number you are calling from, so please call us again when the night shift starts.",
      next: "done",
      onError: "done",
    }),
    new EndFlowModuleExecution({ id: "done" }),
  );
}
