// Generated by @flow-as-code/core codegen from hh-queue-experience-old-town.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  CheckMetricData,
  DequeueContactAndTransferToQueue,
  EndFlowExecution,
  Flow,
  GenericBlock,
  GetParticipantInput,
  InvokeLambdaFunction,
  Loop,
  MessageParticipant,
  MessageParticipantIteratively,
  Refs,
  UpdateContactAttributes,
} from "@flow-as-code/core";

// @keep GENERATED by generators/districts.ts from districts.config.json.
// @keep Edit the config and run `npm run generate`; edits made here are overwritten.
export function hhQueueExperienceOldTown(): Flow {
  return new Flow({
    name: "hh-queue-experience-old-town",
    description: "Queue for the Old Town crew, offering a move to Harborside when that crew is free. Generated from districts.config.json by generators/districts.ts; edit the config, not this flow.",
    connectType: "CUSTOMER_QUEUE",
  }).add(
    new GenericBlock({
      id: "check-moved",
      type: "Compare",
      parameters: { ComparisonValue: "$.Attributes.moved" },
      next: "poll-crews",
      errors: [{ errorType: "NoMatchingCondition", target: "poll-crews" }],
      conditions: [{ target: "settle-in", operator: "Equals", operands: ["true"] }],
    }),
    new Loop({
      id: "poll-crews",
      count: 3,
      onContinue: "check-eta",
      onDone: "settle-in",
    }),
    new InvokeLambdaFunction({
      id: "check-eta",
      lambda: Refs.lambda("crew-eta"),
      timeoutSeconds: 3,
      attributes: { district: "old-town" },
      responseType: "JSON",
      next: "share-eta",
      onError: "check-sibling",
    }),
    new MessageParticipant({
      id: "share-eta",
      text: "The Old Town crew expects to be free in about $.External.etaMinutes minutes.",
      next: "check-sibling",
      onError: "check-sibling",
    }),
    new CheckMetricData({
      id: "check-sibling",
      metric: "NumberOfAgentsAvailable",
      queue: Refs.queue("harborside-crew"),
      branches: [{ operator: "NumberGreaterThan", operand: "0", target: "offer-move" }],
      onNoMatch: "hold",
      onError: "hold",
    }),
    new GetParticipantInput({
      id: "offer-move",
      text: "The Harborside crew has someone free right now. To move to them, press 1. To keep your place here, press 2.",
      timeoutSeconds: 6,
      branches: [
        { digit: "1", target: "note-move" },
        { digit: "2", target: "hold" },
      ],
      onTimeout: "hold",
      onNoMatch: "hold",
      onError: "hold",
    }),
    new UpdateContactAttributes({
      id: "note-move",
      attributes: { district: "harborside", districtName: "Harborside", moved: "true" },
      next: "moving",
      onError: "hold",
    }),
    new MessageParticipantIteratively({
      id: "moving",
      messages: [{ text: "Moving you to the Harborside crew now." }],
      interruptFrequencySeconds: 5,
      onInterrupt: "move-to-sibling",
      onError: "stay-here",
    }),
    new DequeueContactAndTransferToQueue({
      id: "move-to-sibling",
      queue: Refs.queue("harborside-crew"),
      next: "done",
      onQueueAtCapacity: "sibling-full",
      onError: "stay-here",
    }),
    new MessageParticipant({
      id: "sibling-full",
      text: "The Harborside crew just filled up. You still have your place with Old Town.",
      next: "stay-here",
      onError: "stay-here",
    }),
    new UpdateContactAttributes({
      id: "stay-here",
      attributes: { district: "old-town", districtName: "Old Town", moved: "false" },
      next: "hold",
      onError: "hold",
    }),
    new MessageParticipantIteratively({
      id: "hold",
      messages: [
        {
          text: "While you wait: keep the lights on, keep pets close, and stay in a room with a door you can open.",
        },
        { text: "A line of salt across the doorway never hurts. Nor does a cup of tea." },
      ],
      interruptFrequencySeconds: 30,
      onInterrupt: "poll-crews",
      onError: "done",
    }),
    new MessageParticipantIteratively({
      id: "settle-in",
      messages: [
        {
          text: "You are still in line for the $.Attributes.districtName crew, and they know you are waiting.",
        },
        { text: "Keep the lights on and stay with others. A crew member will be with you soon." },
      ],
    }),
    new EndFlowExecution({ id: "done" }),
  );
}
