// Generated by @flow-as-code/core codegen from hh-queue-experience-harborside.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  CheckMetricData,
  Compare,
  DequeueContactAndTransferToQueue,
  EndFlowExecution,
  Flow,
  GetParticipantInput,
  InvokeLambdaFunction,
  Loop,
  MessageParticipant,
  MessageParticipantIteratively,
  Refs,
  UpdateContactAttributes,
  jsonPath,
} from "@flow-as-code/core";

// @keep GENERATED by generators/districts.ts from districts.config.json.
// @keep Edit the config and run `npm run generate`; edits made here are overwritten.
export function hhQueueExperienceHarborside(): Flow {
  return new Flow({
    name: "hh-queue-experience-harborside",
    description: "Queue for the Harborside crew, offering a move to Graveyard Hill when that crew is free. Generated from districts.config.json by generators/districts.ts; edit the config, not this flow.",
    connectType: "CUSTOMER_QUEUE",
  }).add(
    new Compare({
      id: "check-moved",
      value: jsonPath("$.Attributes.moved"),
      branches: [{ operator: "Equals", operands: ["true"], target: "settle-in" }],
      onNoMatch: "poll-crews",
    }),
    new Loop({
      id: "poll-crews",
      count: 3,
      onContinue: "check-eta",
      onDone: "settle-in",
    }),
    new InvokeLambdaFunction({
      id: "check-eta",
      lambda: Refs.lambda("crew-eta"),
      timeoutSeconds: 3,
      attributes: { district: "harborside" },
      responseType: "JSON",
      next: "share-eta",
      onError: "check-sibling",
    }),
    new MessageParticipant({
      id: "share-eta",
      text: "The Harborside crew expects to be free in about $.External.etaMinutes minutes.",
      next: "check-sibling",
      onError: "check-sibling",
    }),
    new CheckMetricData({
      id: "check-sibling",
      metric: "NumberOfAgentsAvailable",
      queue: Refs.queue("graveyard-hill-crew"),
      branches: [{ operator: "NumberGreaterThan", operand: "0", target: "offer-move" }],
      onNoMatch: "hold",
      onError: "hold",
    }),
    new GetParticipantInput({
      id: "offer-move",
      text: "The Graveyard Hill crew has someone free right now. To move to them, press 1. To keep your place here, press 2.",
      timeoutSeconds: 6,
      branches: [
        { digit: "1", target: "note-move" },
        { digit: "2", target: "hold" },
      ],
      onTimeout: "hold",
      onNoMatch: "hold",
      onError: "hold",
    }),
    new UpdateContactAttributes({
      id: "note-move",
      attributes: { district: "graveyard-hill", districtName: "Graveyard Hill", moved: "true" },
      next: "moving",
      onError: "hold",
    }),
    new MessageParticipantIteratively({
      id: "moving",
      messages: [{ text: "Moving you to the Graveyard Hill crew now." }],
      interruptFrequencySeconds: 5,
      onInterrupt: "move-to-sibling",
      onError: "stay-here",
    }),
    new DequeueContactAndTransferToQueue({
      id: "move-to-sibling",
      queue: Refs.queue("graveyard-hill-crew"),
      next: "done",
      onQueueAtCapacity: "sibling-full",
      onError: "stay-here",
    }),
    new MessageParticipant({
      id: "sibling-full",
      text: "The Graveyard Hill crew just filled up. You still have your place with Harborside.",
      next: "stay-here",
      onError: "stay-here",
    }),
    new UpdateContactAttributes({
      id: "stay-here",
      attributes: { district: "harborside", districtName: "Harborside", moved: "false" },
      next: "hold",
      onError: "hold",
    }),
    new MessageParticipantIteratively({
      id: "hold",
      messages: [
        {
          text: "While you wait: keep the lights on, keep pets close, and stay in a room with a door you can open.",
        },
        { text: "A line of salt across the doorway never hurts. Nor does a cup of tea." },
      ],
      interruptFrequencySeconds: 30,
      onInterrupt: "poll-crews",
      onError: "done",
    }),
    new MessageParticipantIteratively({
      id: "settle-in",
      messages: [
        {
          text: "You are still in line for the $.Attributes.districtName crew, and they know you are waiting.",
        },
        { text: "Keep the lights on and stay with others. A crew member will be with you soon." },
      ],
    }),
    new EndFlowExecution({ id: "done" }),
  );
}
