// Generated by @flow-as-code/core codegen from hh-queue-experience-graveyard-hill.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  CheckMetricData,
  Compare,
  CreateCallbackContact,
  DequeueContactAndTransferToQueue,
  DisconnectParticipant,
  DistributeByPercentage,
  EndFlowExecution,
  Flow,
  GetParticipantInput,
  InvokeLambdaFunction,
  Loop,
  MessageParticipant,
  MessageParticipantIteratively,
  Refs,
  TagContact,
  UpdateContactAttributes,
  UpdateContactCallbackNumber,
  jsonPath,
} from "@flow-as-code/core";

// @keep GENERATED by generators/districts.ts from districts.config.json.
// @keep Edit the config and run `npm run generate`; edits made here are overwritten.
export function hhQueueExperienceGraveyardHill(): Flow {
  return new Flow({
    name: "hh-queue-experience-graveyard-hill",
    description: "Queue for the Graveyard Hill crew, offering a move to Old Town when that crew is free. Generated from districts.config.json by generators/districts.ts; edit the config, not this flow.",
    connectType: "CUSTOMER_QUEUE",
  }).add(
    new Compare({
      id: "check-moved",
      value: jsonPath("$.Attributes.moved"),
      branches: [{ operator: "Equals", operands: ["true"], target: "settle-in" }],
      onNoMatch: "pick-hold-variant",
    }),
    new DistributeByPercentage({
      id: "pick-hold-variant",
      branches: [{ percent: 50, target: "note-spoken-variant" }],
      onRemainder: "note-recorded-variant",
    }),
    new UpdateContactAttributes({
      id: "note-spoken-variant",
      attributes: { holdVariant: "spoken" },
      next: "tag-spoken-variant",
      onError: "poll-crews",
    }),
    new TagContact({
      id: "tag-spoken-variant",
      tags: { holdVariant: "spoken" },
      next: "poll-crews",
      onError: "poll-crews",
    }),
    new UpdateContactAttributes({
      id: "note-recorded-variant",
      attributes: { holdVariant: "recorded" },
      next: "tag-recorded-variant",
      onError: "poll-crews",
    }),
    new TagContact({
      id: "tag-recorded-variant",
      tags: { holdVariant: "recorded" },
      next: "poll-crews",
      onError: "poll-crews",
    }),
    new Loop({
      id: "poll-crews",
      count: 3,
      onContinue: "check-eta",
      onDone: "settle-in",
    }),
    new InvokeLambdaFunction({
      id: "check-eta",
      lambda: Refs.lambda("crew-eta"),
      timeoutSeconds: 3,
      attributes: { district: "graveyard-hill" },
      responseType: "JSON",
      next: "share-eta",
      onError: "check-sibling",
    }),
    new MessageParticipant({
      id: "share-eta",
      text: "The Graveyard Hill crew expects to be free in about $.External.etaMinutes minutes.",
      next: "check-eta-band",
      onError: "check-sibling",
    }),
    new Compare({
      id: "check-eta-band",
      value: jsonPath("$.External.etaBand"),
      branches: [{ operator: "Equals", operands: ["later"], target: "offer-callback" }],
      onNoMatch: "check-sibling",
    }),
    new GetParticipantInput({
      id: "offer-callback",
      text: "That is a long wait. For a callback from the next crew that comes free, press 1. To keep your place in line, press 2.",
      timeoutSeconds: 6,
      branches: [
        { digit: "1", target: "set-callback-number" },
        { digit: "2", target: "check-sibling" },
      ],
      onTimeout: "check-sibling",
      onNoMatch: "check-sibling",
      onError: "check-sibling",
    }),
    new UpdateContactCallbackNumber({
      id: "set-callback-number",
      callbackNumber: jsonPath("$.CustomerEndpoint.Address"),
      next: "create-callback",
      onInvalidNumber: "cannot-ring-back",
      onNotDialable: "cannot-ring-back",
    }),
    new MessageParticipant({
      id: "cannot-ring-back",
      text: "We cannot ring you back at the number you are calling from, so we will keep your place in line.",
      next: "hold",
      onError: "hold",
    }),
    new CreateCallbackContact({
      id: "create-callback",
      queue: Refs.queue("dispatch-overflow"),
      initialCallDelaySeconds: 60,
      maximumConnectionAttempts: 2,
      retryDelaySeconds: 600,
      next: "callback-taken",
      onError: "callback-refused",
    }),
    new MessageParticipant({
      id: "callback-refused",
      text: "We cannot take a callback right now, so we will keep your place in line.",
      next: "hold",
      onError: "hold",
    }),
    new MessageParticipant({
      id: "callback-taken",
      text: "You are on the list. A crew will call you back as soon as one comes free. Keep the lights on until then.",
      next: "let-go",
      onError: "let-go",
    }),
    new DisconnectParticipant({ id: "let-go" }),
    new CheckMetricData({
      id: "check-sibling",
      metric: "NumberOfAgentsAvailable",
      queue: Refs.queue("old-town-crew"),
      branches: [{ operator: "NumberGreaterThan", operand: "0", target: "offer-move" }],
      onNoMatch: "hold",
      onError: "hold",
    }),
    new GetParticipantInput({
      id: "offer-move",
      text: "The Old Town crew has someone free right now. To move to them, press 1. To keep your place here, press 2.",
      timeoutSeconds: 6,
      branches: [
        { digit: "1", target: "note-move" },
        { digit: "2", target: "hold" },
      ],
      onTimeout: "hold",
      onNoMatch: "hold",
      onError: "hold",
    }),
    new UpdateContactAttributes({
      id: "note-move",
      attributes: { district: "old-town", districtName: "Old Town", moved: "true" },
      next: "moving",
      onError: "hold",
    }),
    new MessageParticipantIteratively({
      id: "moving",
      messages: [{ text: "Moving you to the Old Town crew now." }],
      interruptFrequencySeconds: 5,
      onInterrupt: "move-to-sibling",
      onError: "stay-here",
    }),
    new DequeueContactAndTransferToQueue({
      id: "move-to-sibling",
      queue: Refs.queue("old-town-crew"),
      next: "done",
      onQueueAtCapacity: "sibling-full",
      onError: "stay-here",
    }),
    new MessageParticipant({
      id: "sibling-full",
      text: "The Old Town crew just filled up. You still have your place with Graveyard Hill.",
      next: "stay-here",
      onError: "stay-here",
    }),
    new UpdateContactAttributes({
      id: "stay-here",
      attributes: { district: "graveyard-hill", districtName: "Graveyard Hill", moved: "false" },
      next: "hold",
      onError: "hold",
    }),
    new Compare({
      id: "hold",
      value: jsonPath("$.Attributes.holdVariant"),
      branches: [{ operator: "Equals", operands: ["recorded"], target: "hold-recorded" }],
      onNoMatch: "hold-spoken",
    }),
    new MessageParticipantIteratively({
      id: "hold-spoken",
      messages: [
        {
          text: "While you wait: keep the lights on, keep pets close, and stay in a room with a door you can open.",
        },
        { text: "A line of salt across the doorway never hurts. Nor does a cup of tea." },
      ],
      interruptFrequencySeconds: 30,
      onInterrupt: "poll-crews",
      onError: "settle-in",
    }),
    new MessageParticipantIteratively({
      id: "hold-recorded",
      messages: [{ prompt: Refs.prompt("salt-line-tips") }],
      interruptFrequencySeconds: 30,
      onInterrupt: "poll-crews",
      onError: "hold-spoken",
    }),
    new MessageParticipantIteratively({
      id: "settle-in",
      messages: [
        {
          text: "You are still in line for the $.Attributes.districtName crew, and they know you are waiting.",
        },
        { text: "Keep the lights on and stay with others. A crew member will be with you soon." },
      ],
    }),
    new EndFlowExecution({ id: "done" }),
  );
}
