// Generated by @flow-as-code/core codegen from hh-greeting-standard.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  EndFlowModuleExecution,
  FlowModule,
  MessageParticipant,
  UpdateContactAttributes,
} from "@flow-as-code/core";

export function hhGreetingStandard(): FlowModule {
  return new FlowModule({
    name: "hh-greeting-standard",
    description: "The greeting outside October. Released through its live alias in envs/seasonal-<environment>.",
    settings: { InputParameters: [], OutputParameters: [], Transitions: [] },
  }).add(
    new MessageParticipant({
      id: "greet",
      text: "Thank you for calling Hollow Hour Removal Co., the night crew for things that go bump. If anyone is hurt or in danger, hang up and call your local emergency number (911 in the US). This call is recorded so our crews can learn from it.",
      next: "set-season",
      onError: "set-season",
    }),
    new UpdateContactAttributes({
      id: "set-season",
      attributes: { season: "standard" },
      next: "done",
      onError: "done",
    }),
    new EndFlowModuleExecution({ id: "done" }),
  );
}
