// Generated by @flow-as-code/core codegen from hh-greeting-halloween.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  EndFlowModuleExecution,
  FlowModule,
  MessageParticipant,
  UpdateContactAttributes,
} from "@flow-as-code/core";

export function hhGreetingHalloween(): FlowModule {
  return new FlowModule({
    name: "hh-greeting-halloween",
    description: "The October greeting. Released through its live alias in envs/seasonal-<environment>.",
    settings: { InputParameters: [], OutputParameters: [], Transitions: [] },
  }).add(
    new MessageParticipant({
      id: "greet",
      text: "Happy Halloween from Hollow Hour Removal Co. October is our busiest month, so every crew is on shift tonight. If anyone is hurt or in danger, hang up and call your local emergency number (911 in the US). This call is recorded so our crews can learn from it.",
      next: "set-season",
      onError: "set-season",
    }),
    new UpdateContactAttributes({
      id: "set-season",
      attributes: { season: "halloween-2026" },
      next: "done",
      onError: "done",
    }),
    new EndFlowModuleExecution({ id: "done" }),
  );
}
